### ISSUE TITLE
Errors when using oauth2 but --cookies-from-browser works on the same video.

### ISSUE THREAD

**Issue by qtlin** [coletdjnz/yt-dlp-youtube-oauth2#36]
```
$ yt-dlp -F --username oauth2 --password '' Video_ID
[youtube+oauth2] Extracting URL: Video_ID
[youtube+oauth2] Video_ID: Downloading webpage
[youtube+oauth2] Video_ID: Downloading ios player API JSON
[youtube+oauth2] Video_ID: Downloading web creator player API JSON
WARNING: [youtube+oauth2] YouTube said: ERROR - Request contains an invalid argument.
WARNING: [youtube+oauth2] HTTP Error 400: Bad Request. Retrying (1/3)...
[youtube+oauth2] Video_ID: Downloading web creator player API JSON
WARNING: [youtube+oauth2] YouTube said: ERROR - Request contains an invalid argument.
WARNING: [youtube+oauth2] HTTP Error 400: Bad Request. Retrying (2/3)...
[youtube+oauth2] Video_ID: Downloading web creator player API JSON
WARNING: [youtube+oauth2] YouTube said: ERROR - Request contains an invalid argument.
WARNING: [youtube+oauth2] HTTP Error 400: Bad Request. Retrying (3/3)...
[youtube+oauth2] Video_ID: Downloading web creator player API JSON
WARNING: [youtube+oauth2] YouTube said: ERROR - Request contains an invalid argument.
WARNING: [youtube+oauth2] Unable to download API page: HTTP Error 400: Bad Request (caused by <HTTPError 400: Bad Request>)
[youtube+oauth2] Video_ID: Downloading m3u8 information
[info] Available formats for Video_ID:
ID  EXT RESOLUTION FPS │   TBR PROTO │ VCODEC        VBR ACODEC     MORE INFO
─────────────────────────────────────────────────────────────────────────────
233 mp4 audio only     │       m3u8  │ audio only        unknown    Default
234 mp4 audio only     │       m3u8  │ audio only        unknown    Default
269 mp4 256x144     15 │  290k m3u8  │ avc1.42C00B  290k video only
229 mp4 426x240     30 │  546k m3u8  │ avc1.4D4015  546k video only
230 mp4 640x360     30 │ 1210k m3u8  │ avc1.4D401E 1210k video only
231 mp4 854x480     30 │ 1569k m3u8  │ avc1.4D401F 1569k video only
232 mp4 1280x720    30 │ 2969k m3u8  │ avc1.4D401F 2969k video only
270 mp4 1920x1080   30 │ 5421k m3u8  │ avc1.640028 5421k video only
$ yt-dlp --username oauth2 --password '' -v --live-from-start -- Video_ID
[debug] Command-line config: ['--username', 'PRIVATE', '--password', 'PRIVATE', '-v', '--live-from-start', '--', 'Video_ID']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.08.06 from yt-dlp/yt-dlp [4d9231208] (pip)
[debug] Python 3.12.5 (CPython x86_64 64bit) - Linux-6.10.6-200.fc40.x86_64-x86_64-with-glibc2.39 (OpenSSL 3.2.2 4 Jun 2024, glibc 2.39)
[debug] exe versions: ffmpeg c30f360 (setts), ffprobe c30f360
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2023.05.07, mutagen-1.47.0, requests-2.32.3, sqlite3-3.45.1, urllib3-1.26.19, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Extractor Plugins: oauth2 (YoutubeClipIE), oauth2 (YoutubeConsentRedirectIE), oauth2 (YoutubeFavouritesIE), oauth2 (YoutubeIE), oauth2 (YoutubeMusicSearchURLIE), oauth2 (YoutubeNotificationsIE), oauth2 (YoutubeSearchDateIE), oauth2 (YoutubeSearchIE), oauth2 (YoutubeSearchURLIE), oauth2 (YoutubeTabIE)
[debug] Plugin directories: ['/home/user/.local/lib/python3.12/site-packages/yt_dlp_plugins']
[debug] Loaded 1830 extractors
[debug] YouTube OAuth2 plugin version 2024.08.31.1
[debug] Loading youtube-oauth2.token_data from cache
[youtube+oauth2] Extracting URL: Video_ID
[youtube+oauth2] Video_ID: Downloading webpage
[youtube+oauth2] Video_ID: Downloading ios player API JSON
[youtube+oauth2] Video_ID: Downloading web creator player API JSON
WARNING: [youtube+oauth2] YouTube said: ERROR - Request contains an invalid argument.
WARNING: [youtube+oauth2] HTTP Error 400: Bad Request. Retrying (1/3)...
[youtube+oauth2] Video_ID: Downloading web creator player API JSON
WARNING: [youtube+oauth2] YouTube said: ERROR - Request contains an invalid argument.
WARNING: [youtube+oauth2] HTTP Error 400: Bad Request. Retrying (2/3)...
[youtube+oauth2] Video_ID: Downloading web creator player API JSON
WARNING: [youtube+oauth2] YouTube said: ERROR - Request contains an invalid argument.
WARNING: [youtube+oauth2] HTTP Error 400: Bad Request. Retrying (3/3)...
[youtube+oauth2] Video_ID: Downloading web creator player API JSON
WARNING: [youtube+oauth2] YouTube said: ERROR - Request contains an invalid argument.
WARNING: [youtube+oauth2] Unable to download API page: HTTP Error 400: Bad Request (caused by <HTTPError 400: Bad Request>)
ERROR: [youtube+oauth2] Video_ID: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 1626, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 1782, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 1841, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 2847, in process_video_result
    self.raise_no_formats(info_dict)
  File "/home/user/.local/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 1123, in raise_no_formats
    raise ExtractorError(msg, video_id=info['id'], ie=info['extractor'],
yt_dlp.utils.ExtractorError: [youtube+oauth2] Video_ID: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

$
```

**Comment by coletdjnz** [comment]
On the README:

> Requires yt-dlp 2024.8.13.232739 (nightly) or above.
